name: Cosmetics-OG
main: plugin.CosmeticsOG
version: 4.6.1
api-version: 1.19
authors: [MediusEcho, NotAlexNoyle]
softdepend: [Vault, SuperVanish, PremiumVanish, VanishNoPacket, PlayerPoints, Citizens, TokenManager]
commands:
  h:
    description: Main command for CosmeticsOG
    aliases: cosmetics
    
