name: Cosmetics-OG
main: cosmeticsOG.CosmeticsOG
version: '${version}'
api-version: '${apiVersion}'
authors: [MediusEcho, NotAlexNoyle]
softdepend: [Vault, SuperVanish, PremiumVanish, VanishNoPacket, PlayerPoints, Citizens, TokenManager]
commands:
  h:
    description: Main command for CosmeticsOG
    aliases: cosmetics
    
