name: ParticleHats
main: com.mediusecho.particlehats.ParticleHats
version: 0.9.2
api-version: 1.19
author: MediusEcho
softdepend: [Vault, SuperVanish, PremiumVanish, PlayerPoints, TokenManager]
commands:
  h:
    description: Main command for ParticleHats
    aliases: ph
